name: zChat
main: ru.gksu.mc.zChat.zChat
depend: [ Vault ]
version: 0.3.1
author: alexanto
website: minecraft.gksu.ru
description: Chat management plugin for zPermissions
permissions:
  zchat.spy:
    description: Allow to listen the all local chat messages
    default: op
  zchat.color:
    description: Allow to use color codes in the messages
    default: op