# Available placeholders: %prefix, %suffix, %world, %displayname, %player, %faction
formats:
    message-format: '[%world] %prefix %player: &f%message'
    # Factions Example, "chatSetFormat": false AND "chatParseTagsAt": "LOW",
    # message-format: '[%world] %prefix <{factions_relcolor}§l{factions_roleprefix}§r{factions_relcolor}{factions_name}§f> %player: &f%message'
    local-message-format: '[LOCAL] %prefix %player: &f%message'
toggles:
    ranged-mode: false
other:
    chat-range: 100.0