name: zChat
main: ru.gksu.mc.zChat.zChat
depend: [Vault]
softdepend: [Factions]
version: 0.3.2
author: alexanto
website: minecraft.gksu.ru
description: Chat management plugin for permissions plugins supporting Vault
commands:
  zchat:
    description: Reloads the zChat configuration
    permission: zchat.reload
    usage: /zchat reload
permissions:
  zchat.reload:
    description: Allows you to reload the zChat configuration
    default: op
  zchat.spy:
    description: Allows you to listen the all local chat messages
    default: op
  zchat.color:
    description: Allows you to use color codes in the messages
    default: op